version: "3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
    restart: always

  springbatch:
    container_name: springbatch
    build: .
    environment:
      MARIADB_ADDRESS: mariadb
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: root
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mariadb